version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: onkoflow-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/onkoflow
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: onkoflow-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


  db:
    image: postgres:14
    container_name: onkoflow-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: onkoflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: onkoflow-redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: onkoflow-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  db-data:
