version: '3.8'

services:
  rrrrrr:
    build:
      context: .
    container_name: onkoflow_webr
    ports:
      - "8000:5000"
    volumes:
      - ./backendd:/app
    networks:
      - onkoflow-net


networks:
  onkoflow-net:
    driver: bridge
