services:
  backend:
    build:
      context: ./backend
    container_name: onkoflow-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
    networks:
      - onkoflow-net

  frontend:
    build:
      context: ./frontend
    container_name: onkoflow-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - onkoflow-net

  llm:
    build:
      context: ./LLM
    container_name: onkoflow-llm
    ports:
      - "5050:5050"
    depends_on:
      - backend
    networks:
      - onkoflow-net

  redis:
    image: redis:7
    container_name: onkoflow-redis
    ports:
      - "6379:6379"
    networks:
      - onkoflow-net

networks:
  onkoflow-net:
    driver: bridge
